# Generated by Django 3.2.7 on 2022-03-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
