# Generated by Django 3.2.7 on 2022-03-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0004_rename_user_id_buildingprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
