# Generated by Django 3.2.7 on 2022-03-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0005_rename_user_buildingprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
